---
- name: Install basic packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - wget
    - vim
    - nano
    - acl
    - openssh-server
    - curl
    - python-apt
    - fail2ban
    - git
    - htop
    - build-essential
    - ufw
    - "{{ base_python_package }}-pip"
  tags: packages
- name: Upgrade pip
  pip:
    name: pip
    version: 9.0.1
  tags: packages
- name: Setup fail2ban
  service:
    name: fail2ban
    state: started
    enabled: yes
  tags: security
- name: Setup SSH service
  block:
    - name: Disable password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        line: 'PasswordAuthentication no'
      notify: restart ssh
      tags: security
    - name: Disable root login
      lineinfile:
        path: /etc/ssh/sshd_config
        line: 'PermitRootLogin no'
      notify: restart ssh
      tags: security
    - name: Disable password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: 'PasswordAuthentication yes'
        state: absent
      notify: restart ssh
      tags: security
    - name: Disable root login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: 'PermitRootLogin yes'
        state: absent
      notify: restart ssh
      tags: security
- name: Setup UFW
  block:
    # Allow only ssh and http(s) ports
    - name: Allow ssh and http(s) connections
      ufw:
        rule: allow
        port: "{{ item }}"
      with_items:
        - "{{ ufw_allowed_ports }}"
      tags: security
    - name: Enable ufw/firewall
      ufw:
        state: enabled
        policy: deny
      tags: security
- name: Install Unattended Upgrades
  apt:
    state: present
    pkg: unattended-upgrades
  tags: packages
- name: Set up unattended upgrades
  copy:
    src: apt_periodic
    dest: /etc/apt/apt.conf.d/10periodic
  tags: security
- name: Automatically remove unused dependencies
  lineinfile:
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: "Unattended-Upgrade::Remove-Unused-Dependencies"
    line: "Unattended-Upgrade::Remove-Unused-Dependencies \"true\";"
    state: present
    create: yes
  tags: security
- name: Setup sudoers file
  template:
    src: sudoers.j2
    dest: /etc/sudoers.d/sudoers
    validate: 'visudo -cf %s'
    mode: 0440
  tags: security
